### ISSUE TITLE
Open brace?

### ISSUE THREAD

**Issue by oschrenk** [jdtsmith/SplitView#1]
Shouldn't this 

```
spoon.splitView:bindHotkeys({choose={mash,"s"},
                             switchFocus={mash,"x"},
                             chooseAppEmacs={mash,"e","Emacs"})
```

be

```
spoon.splitView:bindHotkeys({choose={mash,"s"},
                             switchFocus={mash,"x"},
                             chooseAppEmacs={mash,"e","Emacs"}})
```

Note the added curly brace at the end. If so, the same error is in the README and in the example of the docs) ?

**Comment by oschrenk** [comment]
Happy to do a pull request and submit the change if my assumption is correct. Unfortunately I have troubles running the Spoon (with the added brace). I get 

```
2019-03-12 22:04:39: *** ERROR: /Users/oliver/.hammerspoon/init.lua:497: attempt to index a nil value (global 'spoon')
stack traceback:
	/Users/oliver/.hammerspoon/init.lua:497: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:596: in function 'hs._coresetup.setup'
	(...tail calls...)
```
for 
```
496 mash = {"ctrl", "cmd"}
497 spoon.splitView=hs.loadSpoon("SplitView")
498 spoon.splitView:bindHotkeys({choose={mash,"s"},
499                            switchFocus={mash,"x"}
500                            })
```

And I have to fix that error first.

**Comment by oschrenk** [comment]
Oh, new to Lua, (and Hammerspoon), sorry. `spoon.splitView` relies on some preexisting data structure called `spoon` in your config. Without that it runs - now off to finetuning.

**Comment by jdtsmith** [comment]
Thanks!  Fixed.  I believe `loadSpoon` defines `spoon`, so I can see how that error would occur if you haven't already defined or called it.  I changed it to remove the workaround from an earlier bug in `hs.spoons`.
