### ISSUE TITLE
Breaking since upgrade to Lua 5.4

### ISSUE THREAD

**Issue by tanuj-b** [jdtsmith/SplitView#2]
Hi,

Something seems to be breaking. I installed the latest version of hs_asm.axuielements and I think that may have caused this : 

2020-09-24 16:44:32: -- Loading Spoon: SplitView
2020-09-24 16:44:32: -- Loading extension: application
2020-09-24 16:44:32: *** ERROR: /Users/tanujb/.hammerspoon/Spoons/SplitView.spoon/init.lua:32: attempt to call a nil value (method 'searchPath')
stack traceback:
	/Users/tanujb/.hammerspoon/Spoons/SplitView.spoon/init.lua:32: in main chunk
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:651: in function 'require'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:324: in field 'loadSpoon'
	/Users/tanujb/.hammerspoon/init.lua:22: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:702: in function 'hs._coresetup.setup'
	(...tail calls...)

**Comment by jdtsmith** [comment]
What version of HS are you on?  I noticed this too.  Turns out they changed the API of `axuielements` and brought it into the main Hammerspoon umbrella. Follow along [here](https://github.com/Hammerspoon/hammerspoon/issues/2510).

**Comment by jdtsmith** [comment]
I committed a set of updates that make `SplitView` work with HS 0.9.79 and later, with the in-built `hs.axuielement` (which has quite a few interface changes).  You don't need to install `hs._asm.axuielements` any longer so you can safely delete that.  I also cleaned up a bit of the logic when invoking the split-view menu on the zoom button, added some timeouts and max-iteration protections.  Should be more robust and is quite a bit faster. 

Can you give a try let me know how it's working for you?  If all's well I'll roll a release (just clone and link the `SplitView.spoon` directory into `~/.hammerspoon/Spoons`).   I should mention that MacOS10.15 or higher is now required.

**Comment by tanuj-b** [comment]
Hey JD!

This worked great for me. I think you’re good to go. Thank you for fixing this. This helps a lot!

Thanks,

Tanuj Bhojwani

**Comment by jdtsmith** [comment]
Thanks for the report; [1.6.0 is released](https://github.com/jdtsmith/SplitView/releases/tag/1.6.0).
